language: bash
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - debian-sid # Needed for shellcheck
    packages:
    - shellcheck
    - python-docutils # Needed for rst2man
    - jq # Needed for parsing response from GitHub API

env:
  global:
    - secure: "dFVeGQy4ngj5IgSyvZZpHn1r+AycBR6v8UMMQ/COkXfsPNuiTjAoO5VeVc2RibOT7TCs5w5pp5z/uRE8GBAif+Lrpt2KPkDr1eIoq6epgBi5LhF68wWLnLZVTNir3Tba0QFU4auO68PRbLQvjujkql3u8NIH6EStF03ypuwQzr8/jddTxW0sFqSBkC1O3EE5kgzY8GvW/UOI9PD+2ebEUBSCJBvpYqmpEnL9NOcUHvITWhJXT0q0qulJau1BbmMUT5uIHBnQ0A5HCcMJmRPfDOF/qYnhg4pKOjWsSOwA5itSKgdVxuAIabQ4L3FIKOGmw5mDGTsh1PpQwLD2Bfj0vjw/WhZNgXKzh5BRx/sBzh6tyZ9xfAd9eKWaMsG3shvJfPlCMGCgQGLc/+4fVRl/VNPyjFg1nEGa1wM9UwHc7J2wPn6GDQwmXCViKs/exvfkdJtm3CqnnE/4U+1jWAjbArmBWgDd/G71ytWgG3tPnrG9mQZfS+NgM61BxmMLkTh1zTYrdv6UoLrJXXW2atSkRPiV6GpcRegmW939RJ0Ymb4tosH6OrbE0vHAEtRKAzygNM9njRYkx4hO0tmPTaTpRDF/JCg7mu9OkgwfmK9L5ouJ3SfwxKnKZE/dY4KxJq8+asYJ2VNic70cz4Aq2X6/mZ4vDurPBv6/wdtre/9zc5g="
    - secure: "Xlygj3468iR19fEKYWdKjo97g247RSmjgTOKdS9MHtK7dKYRxr6pbGoq4amUeyZk392Hg0lcNK9X5APHVCt6v2niMzGNbdH5/0+T6Iw0ZLCLKSD9qnucEPV+OW5WElxrpV5vSUcdKXISDX/B1KWz3EdR+jgnqJhCCfTSnXLauMeYOaIR9hg6RvddBhqm8NR6raSq/yf4s+LFh3+nJ97IZLunYp4+WsFU4SHdvgasUTKv/lF8Pr6bzrweSHkT4W8G3usFc1fQt4sDPS9eZzOucLjzAGL1KV8QG5DLtw6xR4bOVwHJnqbc0uho6+WPke4NU0ifoSLUssuxBCOakR6UMe8cun7tdrDEYUqhACAfSlaesdcmNA1RzIZSphQmubW0KsvcQDqRpLWrzgqDEQV5+JZ/8B85eZ1/k5LAwwLCSp+6RW9T8YbAiLGgqBfLMEh1V3BynZOPG/q8hDRtEV4PPEZuyb6M7mUjY062nJppK8wIL13J0MkXwFFYquANN7+jxy6xHBauWwxUHUMJyzbf0bseon0dLh62TpvF4XEohBWbE7ibLey98JwYaEcn+NbdPr1FxBdbT195PY4FO1fz5IZMZWgES8dqbkKI0FBApTXlYkLYMocOlBVBSfW4mSNZokNzu/1w2c6N+MdIoKEvhail9CbrSRhgOs9VjsF2nc4="
  matrix:
    - DIST=regular DEPLOY_FILE=gf-*.tar.gz
    - DIST=single DEPLOY_FILE=gf.sh

before_install:
  - export PREFIX=$HOME/opt
  - mkdir -p $PREFIX/bin
  - export PATH=$PREFIX/bin:$PATH

install:
  # Install latest release of BUTT for Bash testing
  - |
    latestReleaseURL=$(curl -s --user "$GH_API_USER" https://api.github.com/repos/Internetguru/butt/releases/latest \
      | jq -r ".assets[] \
      | .browser_download_url" \
      | grep \.sh$)
  - curl -sL $latestReleaseURL > $PREFIX/bin/butt
  - chmod +x $PREFIX/bin/butt

before_script:
  - |
    if [[ $DIST == regular ]]; then
      ./configure \
        && make \
        && cat compiled/install \
        && compiled/install \
        && PREFIX=/usr/local make dist
    fi
  - |
    if [[ $DIST == single ]]; then
      ./configure \
        && make distsingle \
        && cp gf.sh $PREFIX/bin/gf
    fi

script:
 - shellcheck gf
 - butt test/test.butt

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: "$DEPLOY_FILE"
    skip_cleanup: true
    file_glob: true
    on:
      repo: InternetGuru/omgf
      tags: true
  - deploy:
    provider: script
    script: "scripts/changelog-latest CHANGELOG.md | scripts/travis-update-release"
    on:
      repo: InternetGuru/omgf
      tags: true

matrix:
  fast_finish: true
